### ISSUE TITLE
Parallelize the DTW process

### ISSUE THREAD

**Issue by Deepakgthomas** [fpetitjean/DBA#6]
I have around 200 time series, but they are of length 30,000. The DBA algorithm just doesn't converge (as expected). Would there be a way to parallelize the DTW process within your algorithm? 
Since I am not from cs background (mechanical engineer), my foundations in time series analysis and coding are a bit weak. However, if you could give me quick walk through on what needs to be done, I suppose I should be able to figure out the solution,

**Comment by fpetitjean** [comment]
Hi Deepak, 
Because DTW's complexity is quadratic with the length, parallelism isn't really going to help with length 30,000. However, you could add a warping window, which would turn it to something manageable. The Cython and the Java (DBAWarpingWindow) versions can do it (the 'w' parameter). 
The higher the value of w, the more warping you allow. The complexity then transforms into L.(2w+1) instead of L². With a length of 30,000 I would aim for w=50 or so but it would depend on your application. 
F

**Comment by Deepakgthomas** [comment]
Thank you for your reply Dr. Petitjean. While trying the warping window approach for series with varying lengths, I just got NANs in my output. I am further investigating the issue but I guess this approach won't work unless the series have same lengths.

**Comment by fpetitjean** [comment]
Hi Deepak, 
There is no theoretical problem with doing average for sequences with different lengths. I have done it in the Python version (https://github.com/fpetitjean/DBA/blob/master/DBA.py). Is the problem with that code that you also want to use a warping window and/or multivariate series? If yes let me know and I'll add it to my todolist. 
F

**Comment by Deepakgthomas** [comment]
Hello Dr. Petitjean,

Thank you for your reply. I did try your DBA implementation without warping
and I found that the algorithm never converged. I am guessing this was
because of DTW's O(n^2) complexity. I believe having a warping window might
reduce the time complexity. I highly appreciate your help and I believe I
can assist you code the same if you could give me an idea on how to address
the problem.

**Comment by fpetitjean** [comment]
Which language are you using?

**Comment by Deepakgthomas** [comment]
I am most comfortable with Python. Also, I have some experience with R and
Matlab.

**Comment by fpetitjean** [comment]
Basically there are 3 main functionalities but unfortunately I've developed them as people have asked and I haven't had time to create a single version with all of them. These are:
1. series with multiple lengths
2. multi-variate series (series where each element has multiple values)
3. warping window: additional parameter that allows warping to be limited (and complexity greatly reduced)
Number 1 is in DBA.py, number 2 is in DBA_multi-variate.py and number 3 is in DBAWarpingWindow.java. 

I would start from DBA_multi-variate.py and add:
- make data be in an array of 2D matrices, instead of in a 3D matrix, which would give you functionality 1
- adapt the recurrence in the for i, for j in the loops from java to python with the additional parameter to get functionality 3. 
This all would only take me 40min or so but I unfortunately don't have that in the next week or so :(
Cheers, 
François
