### ISSUE TITLE
Averaging series with different lengths

### ISSUE THREAD

**Issue by xman236** [fpetitjean/DBA#7]
Hi,

I have been playing around with the library by trying to plot the average series. It is clearly visible that the average series is not correct. For any advice I would be greatful. 
```
n_dims = 1

t1=[106.7, 106.7, 99.94, 95.83, 92.84, 90.44, 88.3, 86.12, 82.22, 77.2]
t1_T = np.reshape(t1,(1,-1))
t2= [127.8, 127.8, 122.5, 117.4, 112.2, 107.2, 102.3, 97.47, 92.77, 88.2, 83.79, 79.53, 75.43, 71.49, 67.69, 64.02, 60.42, 56.87, 53.3, 49.6, 45.64, 41.24, 36.27, 30.97, 25.83, 21.09, 16.69, 12.58, 8.671, 4.92, 1.294]
t2_T = np.reshape(t2,(1,-1))
series = [t1_T,t2_T]

plt.figure()
#plotting the synthetic data
plt.plot(range(0,len(t1)), t1 ,label='synthetic data')
plt.plot(range(0,len(t2)), t2 ,label='synthetic data')
plt.legend()

#calculating average series with DBA
average_series = DBA.performDBA(series)

#plotting the average series
for d in range(0,n_dims):
    plt.plot(range(0,average_series.shape[1]), average_series[d],label='average data')
plt.legend()
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/42341018/74033774-3083ac80-49b7-11ea-9b05-d01872823c70.png)

**Comment by fpetitjean** [comment]
Hi, 
The result doesn't seem improbably to me. What would you expect? 
The average series will have the length of one of the series in the set. You can see that the average goes down lower than the blue one but not as much as the orange one, etc. 
F

**Comment by xman236** [comment]
Thank you for the reply,

yes, apparently the first dataset in the series has the reference set role. So I changed series=[t1_T,t2_T] to series=[t2_T, t1_T] :

![image](https://user-images.githubusercontent.com/42341018/74175318-e4926b00-4c35-11ea-91dc-fbed50c7cfd7.png)

In this case, I do not understand why the average data does not go lower in the area x=10-25 and dramatically goes lower afterwards.

**Comment by fpetitjean** [comment]
Hi, 
The reason why I think it doesn't is because all the points of the average series have to align with some points of the blue sequence. As a result, the average is kind of 'waiting' in that flat section, so that it doesn't have to have too many points of itself aligned with the last point of the blue sequence. 
More generally, you should ask yourself what result would you have expected. I would also note that finding an average is similar to finding a model that represent the data and in your case the series are very different, which makes it quite likely that the average wouldn't represent them well (as would be the case in Euclidean space). Cheers, F
